kurs_service/insurance/urls.py
from django.urls import path
from . import views


app_name = "insurance"


urlpatterns = [
    path('', views.insurance, name='insurance'),
]

kurs_service/kurs_service/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap
from .views import robots_txt
from site_login.views import site_logout


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
	path('base-page/', include('base_page.urls', namespace='base_page')),
	path('photo-gallery/', include('photo_gallery.urls', namespace='photo_gallery')),
	path('warranty/', include('warranty.urls', namespace='warranty')),
	path('contacts/', include('contacts.urls', namespace='contacts')),
	path('rules-personal-data/', include('rules_personal_data.urls', namespace='rules_personal_data')),
	path('about/', include('about.urls', namespace='about')),
	path('site/login', include('site_login.urls', namespace='site_login')),
	path('site/signup', include('site_signup.urls', namespace='site_signup')),
	path('reviews/', include('reviews.urls', namespace='reviews')),
	path('discounts/', include('discounts.urls', namespace='discounts')),
	path('news/', include('news.urls', namespace='news')),
	path('insurance/', include('insurance.urls', namespace='insurance')),
	path('evacuation/', include('evacuation.urls', namespace='evacuation')),
	path('diagnostics/', include('diagnostics.urls', namespace='diagnostics')),
	path('online-appointment/', include('online_appointment.urls', namespace='online_appointment')),
	path('price-maintenance/', include('price_maintenance.urls', namespace='price_maintenance')),
	path('price-shod-razval/', include('price_shod_razval.urls', namespace='price_shod_razval')),
	path('price-tire-fitting/', include('price_tire_fitting.urls', namespace='price_tire_fitting')),
	path('check-list/', include('check_list.urls', namespace='check_list')),
	
	path("logout/", site_logout, name="site_logout"),

	path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
	path('robots.txt', robots_txt, name='robots_txt'),

]

if settings.DEBUG:
	urlpatterns += debug_toolbar_urls()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kurs_service/news/urls.py
from django.urls import path
from news import views


app_name = "news"


urlpatterns = [
    path('', views.news, name='news'),
]

kurs_service/insurance/models.py
from django.db import models
from django.utils.html import strip_tags


class InsuranceSliderImages(models.Model):
	img = models.ImageField(upload_to="img-slider", null=True, blank=True, verbose_name="Изображение")
	text = models.TextField(null=True, blank=True, verbose_name="Текст")

	def __str__(self):
		clean_text = strip_tags(self.text)
		return clean_text[:40] if clean_text else "Без названия"

	class Meta:
		db_table = "insurance_slider_images"
		verbose_name: str = "текст"
		verbose_name_plural: str = "Изображения с текстом"

	
class InsuranceForm(models.Model):
	surname = models.CharField(max_length=255, verbose_name="Фамилия")
	name = models.CharField(max_length=255, verbose_name="Имя")
	patronymic = models.CharField(max_length=255, blank=True, null=True, verbose_name="Отчество")
	birth_date = models.DateField(blank=True, null=True, verbose_name="Дата рождения")
	driving_experience = models.PositiveIntegerField(default=0, verbose_name="Стаж вождения (лет)")
	vin = models.CharField(max_length=17, verbose_name="VIN")
	car_make = models.CharField(max_length=255, verbose_name="Марка автомобиля")
	car_model = models.CharField(max_length=255, verbose_name="Модель автомобиля")
	engine_power = models.PositiveIntegerField(verbose_name="Мощность двигателя (л.с.)")
	phone_number = models.CharField(max_length=15, verbose_name="Номер телефона")
	email = models.EmailField(verbose_name="Электронная почта")
	date_time = models.DateTimeField(verbose_name="Дата и время")
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")

	def __str__(self):
		return f"{self.surname} {self.name} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"

	class Meta:
		db_table = "insurance_form"
		verbose_name = "Форма страхования"
		verbose_name_plural = "Заявки на страхование"


class InsuranceBenefitsOfInsuringWithUs(models.Model):
	img = models.ImageField(upload_to="img-insurance", null=True, blank=True, verbose_name="Изображение")
	title = models.CharField(max_length=255, null=True, blank=True, verbose_name="Заголовок")
	description = models.TextField(null=True, blank=True, verbose_name="Описание")

	def __str__(self):
		clean_text = strip_tags(self.title)
		return clean_text[:50] if clean_text else "Без названия"
	
	class Meta:
		db_table = "insurance_benefits_of_insuring_with_us"
		verbose_name: str = "текст"
		verbose_name_plural: str = "Преимущества страхования у нас"


class InsuranceFrequentlyAskedQuestions(models.Model):
	question = models.CharField(max_length=255, blank=True, null=True, verbose_name="Вопрос")
	answer = models.TextField(blank=True, null=True, verbose_name="Ответ")

	def __str__(self):
		clean_text = strip_tags(self.question)
		return clean_text[:50] if clean_text else "Без названия"

	class Meta:
		db_table = "insurance_frequently_asked_questions"
		verbose_name: str = "вопрос"
		verbose_name_plural: str = "Часто задаваемые вопросы"


class InsuranceTitles(models.Model):
	form = models.CharField(max_length=255, blank=True, null=True, verbose_name="Заполнение формы")
	benefits_of_insuring_with_us = models.CharField(max_length=255, blank=True, null=True, verbose_name="Преимущества страхования у нас")
	frequently_asked_questions = models.CharField(max_length=255, blank=True, null=True, verbose_name="Часто задаваемые вопросы")

	def __str__(self):
		return "Заголовки"

	class Meta:
		db_table = "insurance_titles"
		verbose_name: str = "заголовок"
		verbose_name_plural: str = "Заголовки"

kurs_service/insurance/forms.py
from django import forms
from .models import InsuranceForm


class InsuranceFormModelForm(forms.ModelForm):
    class Meta:
        model = InsuranceForm
        fields = [
            "surname", "name", "patronymic", "birth_date", "driving_experience",
            "vin", "car_make", "car_model", "engine_power", "phone_number", "email", "date_time",
        ]
        widgets = {
            "surname": forms.TextInput(attrs={"class": "form-control",}),
            "name": forms.TextInput(attrs={"class": "form-control",}),
            "patronymic": forms.TextInput(attrs={"class": "form-control",}),
            "birth_date": forms.DateInput(attrs={"class": "form-control", "type": "date"}),
            "driving_experience": forms.NumberInput(attrs={"class": "form-control",}),
            "vin": forms.TextInput(attrs={"class": "form-control",}),
            "car_make": forms.TextInput(attrs={"class": "form-control",}),
            "car_model": forms.TextInput(attrs={"class": "form-control",}),
            "engine_power": forms.NumberInput(attrs={"class": "form-control",}),
            "phone_number": forms.TextInput(attrs={"class": "form-control",}),
            "email": forms.EmailInput(attrs={"class": "form-control",}),
            "date_time": forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime-local"}),
        }

kurs_service/insurance/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import InsuranceFormModelForm
from .models import (
	InsuranceSliderImages,
	InsuranceBenefitsOfInsuringWithUs,
	InsuranceFrequentlyAskedQuestions,
	InsuranceTitles,
)


def insurance(request):
    if request.method == "POST":
        form = InsuranceFormModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Ваша заявка успешно отправлена! Ожидайте звонка.")
            return redirect("insurance:insurance")
        else:
            messages.error(request, "Ошибка отправки формы. Проверьте введенные данные.")
    else:
        form = InsuranceFormModelForm()
    context = {
        "form": form,
        "title": "Страхование | OOO 'КУРС'",
        "insurance_titles": InsuranceTitles.objects.first(),
        "insurance_slider_images": InsuranceSliderImages.objects.first(),
        "insurance_benefits_of_insuring_with_us": InsuranceBenefitsOfInsuringWithUs.objects.all(),
        "insurance_frequently_asked_questions": InsuranceFrequentlyAskedQuestions.objects.all(),
    }
    return render(request, "insurance/insurance.html", context=context)

kurs_service/insurance/templates/insurance/insurance.html
{% extends "base_page/base_page.html" %} 
{% load static %} 


{% block title %}
{{title }} 
{% endblock title %} 


{% block content %}
<ul class="breadcrumb">
	<li><a href="/">Главная</a></li>
	<li class="active">Страхование</li>
</ul>
<div class="insuranse-container">
	<div class="insuranse">
		<div class="insuranse-title hidden-xs hidden-md">
			<h1>{{ insurance_slider_images.text|safe }}</h1>
		</div>
	</div>
	<div class="form-insurance">
		<h3 class="pretty-header left-right-line-short-header">
			{{ insurance_titles.form }}
		</h3>
		{% if messages %}
			<div class="messages">
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			</div>
		{% endif %}
		<div class="form-insurance">
			<form
				id="w0"
				class="order-insurance-form"
				method="post">
				{% csrf_token %}
				<div class="row">
					<div class="col-lg-4">
						<div class="form-group field-order-insurance-form-surname required">
							<label class="control-label" for="id_surname"> 
								Фамилия 
							</label>
							{{ form.surname }} 
							{% if form.surname.errors %}
								<div class="help-block text-danger">
									{{ form.surname.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-4">
						<div class="form-group field-order-insurance-form-username required">
							<label class="control-label" for="id_name">
								Имя
							</label>
							{{ form.name }} 
							{% if form.name.errors %}
								<div class="help-block text-danger">
									{{ form.name.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-4">
						<div class="form-group field-order-insurance-form-patronymic required">
							<label class="control-label" for="id_patronymic">
								Отчество
							</label>
							{{ form.patronymic }} 
							{% if form.patronymic.errors %}
								<div class="help-block text-danger">
									{{ form.patronymic.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-2">
						<div class="form-group field-order-insurance-form-age required">
							<label class="control-label" for="id_birth_date">
								Дата рождения
							</label>
							{{ form.birth_date }} 
							{% if form.birth_date.errors %}
								<div class="help-block text-danger">
									{{ form.birth_date.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-2">
						<div class="form-group field-order-insurance-form-driving_experience required">
							<label class="control-label" for="id_driving_experience">
								Стаж вождения
							</label>
							{{ form.driving_experience }} 
							{% if form.driving_experience.errors %}
								<div class="help-block text-danger">
									{{ form.driving_experience.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-4">
						<div class="form-group field-order-insurance-form-vin required">
							<label class="control-label" for="id_vin"> 
								VIN 
							</label>
							{{ form.vin }} 
							{% if form.vin.errors %}
								<div class="help-block text-danger">
									{{ form.vin.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-2">
						<div class="form-group field-order-insurance-form-car_make required">
							<label class="control-label" for="id_car_make">
								Марка автомобиля
							</label>
							{{ form.car_make }} 
							{% if form.car_make.errors %}
								<div class="help-block text-danger">
									{{ form.car_make.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-2">
						<div class="form-group field-order-insurance-form-car_model required">
							<label class="control-label" for="id_car_model">
								Модель автомобиля
							</label>
							{{ form.car_model }} 
							{% if form.car_model.errors %}
								<div class="help-block text-danger">
									{{ form.car_model.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-3">
						<div class="form-group field-order-insurance-form-engine_power required">
							<label class="control-label" for="id_engine_power">
								Мощность двигателя
							</label>
							{{ form.engine_power }} 
							{% if form.engine_power.errors %}
								<div class="help-block text-danger">
									{{ form.engine_power.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-3">
						<div class="form-group field-order-insurance-form-call_number required">
							<label class="control-label" for="id_phone_number">
								Номер телефона
							</label>
							{{ form.phone_number }} 
							{% if form.phone_number.errors %}
								<div class="help-block text-danger">
									{{ form.phone_number.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-3">
						<div class="form-group field-order-insurance-form-email required">
							<label class="control-label" for="id_email">
								Адрес электронной почты
							</label>
							{{ form.email }} 
							{% if form.email.errors %}
								<div class="help-block text-danger">
									{{ form.email.errors.0 }}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="col-lg-3">
						<div class="form-group field-datetimepicker required">
							<label class="control-label" for="datetimepicker">
								Выберите дату и время
							</label>
							{{ form.date_time }}
							{% if form.date_time.errors %}
								<div class="help-block text-danger">
									{{ form.email.errors.0 }}
								</div>
							{% endif %}
							<div class="help-block"></div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-3 col-lg-offset-9">
						<button type="submit" class="kursStyleButton">
							Жду звонка
						</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="benefits-insurance">
		<h3 class="pretty-header left-right-line-short-header">
			{{ insurance_titles.benefits_of_insuring_with_us }}
		</h3>
		<div class="row centered">
			<div id="list-wrapper" class="list-wrapper">
				{% for item in insurance_benefits_of_insuring_with_us %}
				<div data-key="{{ forloop.counter }}">
					<div class="col-lg-3">
						<img src="{{ item.img.url }}" alt="" />
						<h4>{{ item.title|safe }}</h4>
						<p>{{ item.description|safe }}</p>
					</div>
				</div>
				{% endfor %}
				<div style="clear: both; float: none"></div>
			</div>
		</div>
	</div>
	<div class="faq">
		<h3 class="pretty-header left-right-line-short-header">
			{{ insurance_titles.frequently_asked_questions }}
		</h3>
		<div class="wrapper-faq">
			<div id="list-wrapper" class="list-wrapper">
				{% for item in insurance_frequently_asked_questions %}
				<div data-key="{{ forloop.counter }}">
					<div class="item-faq">
						<div
							data-toggle-id="answer-{{ forloop.counter }}"
							class="question arrow"
						>
							<h4 class="title-question">
								{{ item.question|safe }}
							</h4>
						</div>
						<div id="answer-{{ forloop.counter }}" class="answer" hidden>
							<p>{{ item.answer|safe }}</p>
						</div>
					</div>
				</div>
				{% endfor %}
				<div style="clear: both; float: none"></div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}